name: reclaim-tiktok
dependencies:
  - python=3.10
  - flake8
  - black
  - isort
  - pre-commit
  - langchain
  - pandas
  - python-dotenv
  - notebook
  - hdbscan
  - matplotlib
  - scikit-learn
  - numpy
  - pyodbc
  - pip:
    - black[jupyter]
    - newsapi-python
    - langchain-openai
    - scikit-learn
    - TikTokApi
    - browser_cookie3
    - pyktok
    - webvtt-py
    - papermill
    - moviepy
    - azure-cognitiveservices-speech
    - beautifulsoup4
    - azure-identity
